[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"]